### PR TITLE
Issue #8: Rename language to langcode.

### LINKED ISSUE #8: Rename "language" to "langcode" in database and code
An early Backdrop API change (one we inherited from D8) changed "language" to "langcode" everywhere that a string is used to represent language. Although it looks like Redirect is mostly working fine regardless of this change, Redirect itself is still using "language" in the database and in code. For consistency with Backdrop core, it'd be great to get these references updated to match.

### PR DESCRIPTION
**Pull request by quicksketch**
Fixes https://github.com/backdrop-contrib/redirect/issues/8.

### CODE REVIEW

**Comment by quicksketch** [comment]
This PR also includes https://github.com/backdrop-contrib/redirect/pull/12, as they had a little overlap.

**Comment by serundeputy** [comment]
@quicksketch this one seems to have broken my local:

```
Error message
PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'langcode' in 'where clause': SELECT redirect.rid AS rid FROM {redirect} redirect WHERE ( (source LIKE :db_condition_placeholder_0 ESCAPE '\\') OR (source = :db_condition_placeholder_1) )AND (langcode IN (:db_condition_placeholder_2, :db_condition_placeholder_3)) ; Array ( [:db_condition_placeholder_0] => backdrops [:db_condition_placeholder_1] => [:db_condition_placeholder_2] => en [:db_condition_placeholder_3] => und ) in redirect_load_by_source() (line 547 of /Users/geoff/Sites/serundrop/modules/contrib/redirect/redirect.module).
```

maybe because I merged in Issue 11 before this one?

**Comment by serundeputy** [comment]
@quicksketch i see a db update was required; thanks again!

**Comment by quicksketch** [comment]
> i see a db update was required; thanks again!

Yes! Excellent, so everything is working? I think this is good for a release! It's working well on the BackdropCMS.org dev site I have locally at least. :+1:

**Comment by serundeputy** [comment]
@quicksketch yes; everything is working on my local;  thanks :+1:

**Pull request merged**
